### ISSUE TITLE
项目链接

### ISSUE THREAD

**Issue by mrlinyj** [FLHonker/Awesome-Knowledge-Distillation#1]
感谢您的分享，
就提个建议，如果有项目链接就很更好了

**Comment by mrlinyj** [comment]
https://github.com/dkozlov/awesome-knowledge-distillation  这个也很不错

**Comment by FLHonker** [comment]
感谢建议，所有的pdf在arXiv上都是可以下载的，文章链接就不放了，后面会把code开源的项目链接加上的
