### ISSUE TITLE
One more paper

### ISSUE THREAD

**Issue by angpo** [FLHonker/Awesome-Knowledge-Distillation#21]
Would you mind adding this paper to the "Applications of KD" section?

_How many Observations are Enough? Knowledge Distillation for Trajectory Forecasting_. Monti, Alessio et al. CVPR 2022

**Comment by fawazsammani** [comment]
I read this paper today, would you mind to add it to the list so it is possible to refer to it when needed, through this repo.....

Knowledge Distillation as Efficient Pre-training: Faster Convergence, Higher Data-efficiency, and Better Transferability, CVPR 2020
https://arxiv.org/pdf/2203.05180v2.pdf
