### ISSUE TITLE
One more paper

### ISSUE THREAD

**Issue by xialeiliu** [FLHonker/Awesome-Knowledge-Distillation#3]
Could you help to add this paper belonging to structured distillation I think:

Yu, Lu, Vacit Oguz Yazici, Xialei Liu, Joost van de Weijer, Yongmei Cheng, and Arnau Ramisa. "Learning Metrics from Teachers: Compact Networks for Image Embedding." In Proceedings of the IEEE Conference on Computer Vision and Pattern Recognition, pp. 2907-2916. 2019.

**Comment by xialeiliu** [comment]
I found it, thanks.

**Comment by FLHonker** [comment]
[image: image.png]


Xialei Liu <notifications@github.com> 于2020年2月19日周三 下午7:12写道：
