### ISSUE TITLE
关于推荐

### ISSUE THREAD

**Issue by ZainZhao** [FLHonker/Awesome-Knowledge-Distillation#6]
您好，感谢分享，感觉目前与推荐相关的paper较少，所以想问问您，是因为这部分内容比较新，还是说有比较严重的问题难以开展研究？

**Comment by FLHonker** [comment]
> 您好，感谢分享，感觉目前与推荐相关的paper较少，所以想问问您，是因为这部分内容比较新，还是说有比较严重的问题难以开展研究？

本仓库主要收集CV相关的paper，发现有新paper欢迎贡献~
推荐上所用的KD方法基本上是从CV迁过去的，方法上不算很新，也没有难以解决的问题，可能创新度不够吧。

**Comment by ZainZhao** [comment]
> > 您好，感谢分享，感觉目前与推荐相关的paper较少，所以想问问您，是因为这部分内容比较新，还是说有比较严重的问题难以开展研究？
> 
> 本仓库主要收集CV相关的paper，发现有新paper欢迎贡献~
> 推荐上所用的KD方法基本上是从CV迁过去的，方法上不算很新，也没有难以解决的问题，可能创新度不够吧。

好的，非常感谢，如果能单独划分出`检索&推荐`的子标题就更好了

**Comment by FLHonker** [comment]
no problem
