### ISSUE TITLE
about kd paper in rec sys

### ISSUE THREAD

**Issue by ZainZhao** [FLHonker/Awesome-Knowledge-Distillation#9]
Thank u for your contribution.
Cloud i create a new branch that add a category “kd in rec”?
 thank u again!

**Comment by FLHonker** [comment]
> Thank u for your contribution.
> Cloud i create a new branch that add a category “kd in rec”?
> thank u again!

You'd better to create a new subsection before 'beyound' following my format, thanks!

**Comment by FLHonker** [comment]
> Thank u for your contribution.
> Cloud i create a new branch that add a category “kd in rec”?
> thank u again!

How many papers about RecSys have you sorted? Could you please transfer them to me or add to the repository?
